name: tests

on:
  push:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      
    - name: Set up PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
        postgresql db: 'market'
    
    - name: Copy secret
      env:
        SECRET: ${{ secrets.SECRET }}
      run: |
        echo `echo $SECRET | base64 --decode` > config/secret.json
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install coverage and codecov
      run: |
        pip install coverage
        pip install codecov
    
    - name: Run migrations
      run: |
        python manage.py migrate
    
    - name: Run tests
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        coverage run -a manage.py test markets.tests
        coverage run -a manage.py test users.tests
        coverage report
        codecov -t $CODECOV_TOKEN
