name: Run tests

on:
  push:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      
    - name: Set up PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
    
    - name: Copy secret
      env:
        SECRET: ${{ secrets.SECRET }}
      run: |
        echo `echo $SECRET | base64 --decode` > config/secret.json
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install coverage
      run: |
        pip install coverage
   
    - name: Create database
      run: |
        su - postgres
        createdb market
    
    - name: Run migrations
      run: |
        python manage.py migrate --settings=config.settings.local
        python manage.py makemigrations backend --settings=config.settings.local
        python manage.py makemigrations users --settings=config.settings.local
        python manage.py migrate --settings=config.settings.local
    
    - name: Run tests
      run: |
        coverage run -a manage.py test backend.tests --settings=config.settings.local
        coverage run -a manage.py test users.tests --settings=config.settings.local
        coverage report
